server:
  port: 8091

spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/best_practices?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: mysql123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/best_practices_01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: mysql123456
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.yuan.dynamic.datasource: info