yuan:
  custom:
    enabled: true
    author-link: https://github.com/Hansiyuan131
    author-name: hansiyuan
  system:
    project-name: java-advance

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/best-practices?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql123456
    driver-class-name: com.mysql.cj.jdbc.Driver